services:
  backend:
    volumes:
      - ./backend:/app:cached
      - backend_venv:/app/env
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - RELOAD=true
    command: ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--log-level", "debug"]

  frontend:
    volumes:
      - ./frontend:/app:cached
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_HMR_HOST=localhost
      - VITE_HMR_CLIENT_PORT=80
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]

  # Include nginx in development for consistent routing
  nginx:
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  backend_venv:
  mongodb_data:
